// <auto-generated />
using C_3PO.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C_3PO.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211219143436_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("C_3PO.Data.Models.Onboarding", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ActionMessage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("CategoriesMessage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Channel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("NotificationsMessage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("OfferMessage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RulesMessage")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Onboardings");
                });
#pragma warning restore 612, 618
        }
    }
}
